::katana_contracts::contract!(
    ControllerLatest,
    "{CARGO_MANIFEST_DIR}/controller/account_sdk/artifacts/classes/controller.latest.\
     contract_class.json"
);
::katana_contracts::contract!(
    ControllerV104,
    "{CARGO_MANIFEST_DIR}/controller/account_sdk/artifacts/classes/controller.v1.0.4.\
     contract_class.json"
);
::katana_contracts::contract!(
    ControllerV105,
    "{CARGO_MANIFEST_DIR}/controller/account_sdk/artifacts/classes/controller.v1.0.5.\
     contract_class.json"
);
::katana_contracts::contract!(
    ControllerV106,
    "{CARGO_MANIFEST_DIR}/controller/account_sdk/artifacts/classes/controller.v1.0.6.\
     contract_class.json"
);
::katana_contracts::contract!(
    ControllerV107,
    "{CARGO_MANIFEST_DIR}/controller/account_sdk/artifacts/classes/controller.v1.0.7.\
     contract_class.json"
);
::katana_contracts::contract!(
    ControllerV108,
    "{CARGO_MANIFEST_DIR}/controller/account_sdk/artifacts/classes/controller.v1.0.8.\
     contract_class.json"
);
::katana_contracts::contract!(
    ControllerV109,
    "{CARGO_MANIFEST_DIR}/controller/account_sdk/artifacts/classes/controller.v1.0.9.\
     contract_class.json"
);
