[package]
edition.workspace = true
name = "katana-rpc-api-macro"
version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = [ "extra-traits", "full", "parsing", "printing", "proc-macro", "visit-mut" ] }
