[workspace]
members = ["contracts/amd_tee_registry", "contracts/katana_tee"]

[[tool.snforge.fork]]
name = "SEPOLIA_LATEST"
url = "https://api.zan.top/public/starknet-sepolia/rpc/v0_10"
block_id.tag = "latest"