[workspace]
members = ["contracts/amd_tee_registry", "contracts/katana_tee", "contracts/scripts"]

[[tool.snforge.fork]]
name = "SEPOLIA_LATEST"
url = "$STARKNET_RPC_URL_SEPOLIA"
block_id.tag = "latest"

[lib]
sierra = true
casm = true