[paymaster-service]
repo = "https://github.com/cartridge-gg/paymaster"
rev = "788aeac" # main
package = "paymaster-service"

[vrf-server]
repo = "https://github.com/cartridge-gg/vrf.git"
rev = "8490dee" # main
package = "vrf-server"
