[paymaster-service]
repo = "https://github.com/cartridge-gg/paymaster"
rev = "4346827" # copenhagen-4cb4
package = "paymaster-service"

[vrf-server]
repo = "https://github.com/cartridge-gg/vrf.git"
rev = "6d1c0f6"
package = "vrf-server"
