// Placeholder - will be generated by: katana-tee generate-cairo-fixtures
// Run: cargo run -p katana_tee_client --bin katana-tee -- generate-cairo-fixtures
// Output path: contracts/amd_tee_registry/tests/test_journal_decode_from_fixtures/test_journal_decode_fixtures.cairo

use amd_tee_registry::tee_types::{VerifierJournal, VerificationResult};

// Temporary stub implementations until real fixtures are generated
pub fn get_block_0_inputs() -> Array<u256> {
    // TODO: Replace with generated fixture
    array![]
}

pub fn get_block_0_expected() -> VerifierJournal {
    // TODO: Replace with generated fixture
    VerifierJournal {
        result: VerificationResult::Success,
        timestamp: 0,
        processor_model: 0,
        raw_report: array![].span(),
        certs: array![],
        cert_serials: array![],
        trusted_certs_prefix_len: 0,
    }
}

pub fn get_block_1_inputs() -> Array<u256> {
    array![]
}

pub fn get_block_1_expected() -> VerifierJournal {
    VerifierJournal {
        result: VerificationResult::Success,
        timestamp: 0,
        processor_model: 0,
        raw_report: array![].span(),
        certs: array![],
        cert_serials: array![],
        trusted_certs_prefix_len: 0,
    }
}

pub fn get_block_2_inputs() -> Array<u256> {
    array![]
}

pub fn get_block_2_expected() -> VerifierJournal {
    VerifierJournal {
        result: VerificationResult::Success,
        timestamp: 0,
        processor_model: 0,
        raw_report: array![].span(),
        certs: array![],
        cert_serials: array![],
        trusted_certs_prefix_len: 0,
    }
}
