[package]
edition.workspace = true
license.workspace = true
name = "katana-contracts"
repository.workspace = true
version.workspace = true

[dependencies]
katana-contracts-macro = { path = "macro" }
katana-primitives.workspace = true
starknet.workspace = true

thiserror.workspace = true
