//! Test vector generator for verify_katana_report_data
//!
//! This test generates test vectors that can be used in Cairo unit tests.
//! It uses the same Poseidon hash implementation as the Katana TEE RPC.
//!
//! Run with: cargo test -p katana_tee_client --test generate_report_data_vectors -- --nocapture

use starknet_rust_core::crypto::HashFunction;
use starknet_rust_core::types::Felt;

/// Convert a u128 to hex string (without 0x prefix)
fn u128_to_hex(v: u128) -> String {
    format!("{:032x}", v)
}

/// Compute report_data from state_root and block_hash (matches Katana RPC implementation)
fn compute_report_data(state_root: Felt, block_hash: Felt) -> [u8; 64] {
    // Compute Poseidon hash of state_root and block_hash
    let commitment = HashFunction::poseidon().hash(state_root, block_hash);

    // Convert Felt to bytes (32 bytes) and pad to 64 bytes
    let commitment_bytes = commitment.to_bytes_be();

    let mut report_data = [0u8; 64];
    // Place the 32-byte hash in the first half
    report_data[..32].copy_from_slice(&commitment_bytes);
    // Second half remains zeros

    report_data
}

/// Convert report_data bytes to u512 limbs (as Cairo sees it)
fn report_data_to_u512_limbs(report_data: &[u8; 64]) -> (u128, u128, u128, u128) {
    // When interpreted as u512 (little-endian limbs):
    // limb0 = bytes[0..16] as little-endian u128
    // limb1 = bytes[16..32] as little-endian u128
    // limb2 = bytes[32..48] as little-endian u128 (should be 0)
    // limb3 = bytes[48..64] as little-endian u128 (should be 0)

    let limb0 = u128::from_le_bytes(report_data[0..16].try_into().unwrap());
    let limb1 = u128::from_le_bytes(report_data[16..32].try_into().unwrap());
    let limb2 = u128::from_le_bytes(report_data[32..48].try_into().unwrap());
    let limb3 = u128::from_le_bytes(report_data[48..64].try_into().unwrap());

    (limb0, limb1, limb2, limb3)
}

/// Byte-reverse a u128 (same as Cairo's u128_byte_reverse)
fn u128_byte_reverse(v: u128) -> u128 {
    v.swap_bytes()
}

/// Verify that our limb extraction matches what Cairo will compute
fn verify_commitment_reconstruction(commitment: Felt, limb0: u128, limb1: u128) {
    // Cairo does: expected_commitment = u256{low: reverse(limb1), high: reverse(limb0)}
    let reconstructed_low = u128_byte_reverse(limb1);
    let reconstructed_high = u128_byte_reverse(limb0);

    let commitment_bytes = commitment.to_bytes_be();
    let expected_high = u128::from_be_bytes(commitment_bytes[0..16].try_into().unwrap());
    let expected_low = u128::from_be_bytes(commitment_bytes[16..32].try_into().unwrap());

    assert_eq!(reconstructed_high, expected_high, "High limb mismatch");
    assert_eq!(reconstructed_low, expected_low, "Low limb mismatch");
}

#[test]
fn generate_test_vectors() {
    println!("\n=== Test vectors for verify_katana_report_data ===\n");

    // Test cases with different values
    let cases = [
        (
            Felt::from_hex("0x123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef").unwrap(),
            Felt::from_hex("0x0fedcba9876543210fedcba9876543210fedcba9876543210fedcba98765432").unwrap(),
            "Test case 1: Large values"
        ),
        (
            Felt::from_hex("0x1").unwrap(),
            Felt::from_hex("0x2").unwrap(),
            "Test case 2: Small values"
        ),
        (
            Felt::from_hex("0x04b1a39276c1df7ca78febcb6850f3649e826a3f6618e6ab30b48dcc948de1ad").unwrap(),
            Felt::from_hex("0x06c5e8a47fb34d21c08e4eb6a91fa7bce3f2d5a490c8b7e1d26f43098a5bc7e2").unwrap(),
            "Test case 3: Realistic block data"
        ),
    ];

    println!("// Cairo test file content:");
    println!("// contracts/katana_tee/tests/test_verify_katana_report_data.cairo\n");
    println!("//! Unit tests for verify_katana_report_data function.");
    println!("//!");
    println!("//! These test vectors were generated by:");
    println!("//! cargo test -p katana_tee_client --test generate_report_data_vectors -- --nocapture\n");
    println!("use core::integer::u512;");
    println!("use katana_tee::katana_report_utils::verify_katana_report_data;\n");

    for (i, (state_root, block_hash, description)) in cases.iter().enumerate() {
        let commitment = HashFunction::poseidon().hash(*state_root, *block_hash);
        let report_data = compute_report_data(*state_root, *block_hash);
        let (limb0, limb1, limb2, limb3) = report_data_to_u512_limbs(&report_data);

        // Verify our extraction is correct
        verify_commitment_reconstruction(commitment, limb0, limb1);

        assert_eq!(limb2, 0, "limb2 should be 0");
        assert_eq!(limb3, 0, "limb3 should be 0");

        println!("/// {}", description);
        println!("/// state_root: {:#066x}", state_root);
        println!("/// block_hash: {:#066x}", block_hash);
        println!("/// commitment (poseidon_hash): {:#066x}", commitment);
        println!("#[test]");
        println!("fn test_verify_katana_report_data_case_{}() {{", i + 1);
        println!("    let report_data = u512 {{");
        println!("        limb0: 0x{},", u128_to_hex(limb0));
        println!("        limb1: 0x{},", u128_to_hex(limb1));
        println!("        limb2: 0,");
        println!("        limb3: 0,");
        println!("    }};");
        println!();
        println!("    let state_root: felt252 = {:#066x};", state_root);
        println!("    let block_hash: felt252 = {:#066x};", block_hash);
        println!();
        println!("    let result = verify_katana_report_data(report_data, state_root, block_hash);");
        println!("    assert(result, 'Verification should pass');");
        println!("}}\n");
    }

    // Generate a failing test case (mismatched commitment)
    println!("/// Test case 4: Commitment mismatch (should panic)");
    println!("/// Uses wrong state_root for the report_data");
    println!("#[test]");
    println!("#[should_panic(expected: 'Commitment mismatch')]");
    println!("fn test_verify_katana_report_data_mismatch() {{");
    println!("    // report_data was computed with state_root=0x1, block_hash=0x2");
    let (state_root, block_hash) = (Felt::from_hex("0x1").unwrap(), Felt::from_hex("0x2").unwrap());
    let report_data = compute_report_data(state_root, block_hash);
    let (limb0, limb1, _, _) = report_data_to_u512_limbs(&report_data);
    println!("    let report_data = u512 {{");
    println!("        limb0: 0x{},", u128_to_hex(limb0));
    println!("        limb1: 0x{},", u128_to_hex(limb1));
    println!("        limb2: 0,");
    println!("        limb3: 0,");
    println!("    }};");
    println!();
    println!("    // But we pass different state_root (0x3 instead of 0x1)");
    println!("    let state_root: felt252 = 0x3;");
    println!("    let block_hash: felt252 = 0x2;");
    println!();
    println!("    // This should panic with 'Commitment mismatch'");
    println!("    verify_katana_report_data(report_data, state_root, block_hash);");
    println!("}}");

    println!("\n=== End of test vectors ===\n");
}
