// starknet.js wrapper for the cross-chain game.
//
// Settlement ("L1"): piltover core + score_registry. The settlement account signs
// purchases (L1->L2) and score claims.
// Appchain ("L2"): a single `game` contract — purchase mints a playable game,
// play rolls a score and publishes it to L1. The appchain account signs plays.

import { Account, RpcProvider, hash } from "starknet";
import deployments from "./deployments.json";

export const SETTLEMENT_RPC = deployments.settlement.rpcUrl;
export const APPCHAIN_RPC = deployments.appchain.rpcUrl;
export const SETTLEMENT_EXPLORER = deployments.settlement.explorer;
export const APPCHAIN_EXPLORER = deployments.appchain.explorer;

export const PILTOVER = deployments.settlement.piltover;
export const SCORE_REGISTRY = deployments.settlement.scoreRegistry;
export const GAME = deployments.appchain.game;

export const BUYER_ADDRESS = deployments.settlement.account.address; // signs on L1
export const PLAYER_ADDRESS = deployments.appchain.account.address; // signs on L2

const MINT_GAME_SELECTOR = hash.getSelectorFromName("mint_game");
const GAME_MINTED_KEY = hash.getSelectorFromName("GameMinted");
const GAME_PLAYED_KEY = hash.getSelectorFromName("GamePlayed");
const MESSAGE_SENT_KEY = hash.getSelectorFromName("MessageSent"); // piltover core (L1)
const SCORE_CLAIMED_KEY = hash.getSelectorFromName("ScoreClaimed"); // score_registry (L1)

const sameFelt = (a: string, b: string) => BigInt(a) === BigInt(b);

const settlementProvider = new RpcProvider({ nodeUrl: SETTLEMENT_RPC });
const appchainProvider = new RpcProvider({ nodeUrl: APPCHAIN_RPC });

// Dev keys printed by `katana --dev` / generated by `katana init rollup`.
// Throwaway local keys — never reuse with real funds.
const settlementAccount = new Account({
  provider: settlementProvider,
  address: deployments.settlement.account.address,
  signer: deployments.settlement.account.privateKey,
  cairoVersion: "1",
});
const appchainAccount = new Account({
  provider: appchainProvider,
  address: deployments.appchain.account.address,
  signer: deployments.appchain.account.privateKey,
  cairoVersion: "1",
});

// Purchases and score-claims are both signed by the settlement account, so they
// must not race on the nonce. Serialize them through a promise-chain mutex.
let settlementQueue: Promise<unknown> = Promise.resolve();
function withSettlementLock<T>(fn: () => Promise<T>): Promise<T> {
  const run = settlementQueue.then(fn, fn);
  settlementQueue = run.then(
    () => {},
    () => {},
  );
  return run;
}

async function callFelt(p: RpcProvider, contractAddress: string, entrypoint: string, calldata: string[] = []) {
  const res = await p.callContract({ contractAddress, entrypoint, calldata });
  return BigInt(res[0]);
}

export function explorerTxUrl(explorerBase: string, txHash: string): string {
  return `${explorerBase}/tx/${txHash}`;
}

export function explorerAddrUrl(explorerBase: string, address: string): string {
  return `${explorerBase}/contract/${address}`;
}

export function shortHex(value: string, lead = 6, tail = 4): string {
  if (!value) return "—";
  if (value.length <= lead + tail + 2) return value;
  return `${value.slice(0, lead)}…${value.slice(-tail)}`;
}

// --- Appchain game state ---

export type GameState = {
  totalMinted: number; // games purchased
  available: number; // minted, not yet played
  totalPlayed: number;
  lastScore: number;
};

export async function readGameState(): Promise<GameState> {
  const [minted, avail, played, last] = await Promise.all([
    callFelt(appchainProvider, GAME, "total_minted"),
    callFelt(appchainProvider, GAME, "available"),
    callFelt(appchainProvider, GAME, "total_played"),
    callFelt(appchainProvider, GAME, "last_score"),
  ]);
  return {
    totalMinted: Number(minted),
    available: Number(avail),
    totalPlayed: Number(played),
    lastScore: Number(last),
  };
}

// --- L1 published-score state (settlement score_registry) ---

export type ScoreState = { lastPublished: number; totalPublished: number };

export async function readScoreState(): Promise<ScoreState> {
  if (!SCORE_REGISTRY) return { lastPublished: 0, totalPublished: 0 };
  const [last, total] = await Promise.all([
    callFelt(settlementProvider, SCORE_REGISTRY, "last_score"),
    callFelt(settlementProvider, SCORE_REGISTRY, "total_synced"),
  ]);
  return { lastPublished: Number(last), totalPublished: Number(total) };
}

// --- Phase 1: purchase (L1 -> L2) ---

/** L1 op: send a message via the piltover core to mint a playable game on L2. */
export async function purchaseGame(gameId: number): Promise<string> {
  return withSettlementLock(async () => {
    const { transaction_hash } = await settlementAccount.execute({
      contractAddress: PILTOVER,
      entrypoint: "send_message_to_appchain",
      calldata: [GAME, MINT_GAME_SELECTOR, "1", "0x" + gameId.toString(16)],
    });
    return transaction_hash;
  });
}

type RawEvent = { transaction_hash: string; keys: string[]; data: string[] };

/** Fetch all events for an address + key, oldest-first, following pagination. */
async function fetchEvents(p: RpcProvider, address: string, key: string): Promise<RawEvent[]> {
  const out: RawEvent[] = [];
  let continuationToken: string | undefined;
  for (let page = 0; page < 50; page++) {
    const res = await p.getEvents({
      address,
      from_block: { block_number: 0 },
      to_block: "latest",
      keys: [[key]],
      chunk_size: 100,
      continuation_token: continuationToken,
    });
    for (const ev of res.events) out.push({ transaction_hash: ev.transaction_hash, keys: ev.keys, data: ev.data });
    continuationToken = res.continuation_token;
    if (!continuationToken) break;
  }
  return out;
}

// Event-sourced history so the feeds survive a page refresh (rebuilt from chain
// on every poll instead of living only in volatile React state).

export type PurchaseRecord = {
  seq: number; // 1-based order
  l1TxHash: string; // send_message_to_appchain tx on the settlement layer
  mintTxHash?: string; // relayed mint_game tx on the appchain (once minted)
};

/** Rebuild the purchase list: each L1 `MessageSent` (to the game contract) is a
 *  purchase; the matching `GameMinted` (same FIFO order) is its relayed mint. */
export async function getPurchaseHistory(): Promise<PurchaseRecord[]> {
  const [sent, minted] = await Promise.all([
    fetchEvents(settlementProvider, PILTOVER, MESSAGE_SENT_KEY),
    fetchEvents(appchainProvider, GAME, GAME_MINTED_KEY),
  ]);
  // MessageSent: keys=[selector, message_hash, from, to], data=[selector, nonce, payload_len, ...payload]
  const purchases = sent.filter(
    (e) => e.keys.length >= 4 && sameFelt(e.keys[3], GAME) && sameFelt(e.data[0], MINT_GAME_SELECTOR),
  );
  return purchases.map((e, i) => ({
    seq: i + 1,
    l1TxHash: e.transaction_hash,
    mintTxHash: minted[i]?.transaction_hash,
  }));
}

export type PlayRecord = {
  seq: number;
  score: number;
  l2TxHash: string; // play_game tx on the appchain
  claimTxHash?: string; // claim_score tx on the settlement layer (once published)
};

/** Rebuild the play list: each appchain `GamePlayed` is a play; the matching
 *  settlement `ScoreClaimed` (same FIFO order) is its publish to L1. */
export async function getPlayHistory(): Promise<PlayRecord[]> {
  const [played, claimed] = await Promise.all([
    fetchEvents(appchainProvider, GAME, GAME_PLAYED_KEY),
    SCORE_REGISTRY ? fetchEvents(settlementProvider, SCORE_REGISTRY, SCORE_CLAIMED_KEY) : Promise.resolve([]),
  ]);
  // GamePlayed: keys=[selector, player], data=[game_no, score]
  return played.map((e, i) => ({
    seq: i + 1,
    score: Number(BigInt(e.data[1])),
    l2TxHash: e.transaction_hash,
    claimTxHash: claimed[i]?.transaction_hash,
  }));
}

// --- Phase 2 + 3: play (rolls + publishes to L1 in one tx) ---

/** Play one available game. Rolls on chain and emits the score to L1. Returns
 *  the L2 tx hash, the block it landed in, and the rolled score (from the event). */
export async function playGame(): Promise<{ txHash: string; block: number; score: number }> {
  const { transaction_hash } = await appchainAccount.execute({
    contractAddress: GAME,
    entrypoint: "play_game",
    calldata: [],
  });
  const receipt: any = await appchainProvider.waitForTransaction(transaction_hash);
  const events: any[] = receipt?.events ?? [];
  const played = events.find((e) => e.keys?.[0] === GAME_PLAYED_KEY);
  // GamePlayed: keys=[selector, player], data=[game_no, score]
  const score = played ? Number(BigInt(played.data[1])) : 0;
  const block = await appchainProvider.getBlockNumber();
  return { txHash: transaction_hash, block, score };
}

/** Current appchain block height. */
export async function appchainBlock(): Promise<number> {
  return appchainProvider.getBlockNumber();
}

/** Block height settled onto the piltover core by saya (get_state()[1]). */
export async function settledBlock(): Promise<number> {
  const res = await settlementProvider.callContract({
    contractAddress: PILTOVER,
    entrypoint: "get_state",
    calldata: [],
  });
  const bn = BigInt(res[1]);
  return bn > 0xffffffffffffffffn ? -1 : Number(bn);
}

/** L1 op: consume the settled score on the settlement layer (auto, after a play). */
export async function claimScore(player: string, score: number): Promise<string> {
  return withSettlementLock(async () => {
    const { transaction_hash } = await settlementAccount.execute({
      contractAddress: SCORE_REGISTRY,
      entrypoint: "claim_score",
      // claim_score(from_address = game contract, player, score)
      calldata: [GAME, player, "0x" + score.toString(16)],
    });
    await settlementProvider.waitForTransaction(transaction_hash);
    return transaction_hash;
  });
}
