// Frontend data layer for the cross-chain game (Dojo + Torii edition).
//
// Settlement ("L1"): piltover core + the `score` Dojo world (score_registry
// system). The settlement account signs purchases (L1->L2) and score claims.
// Appchain ("L2"): the `game` Dojo world (game system) — purchase mints a
// playable game, play rolls a score and publishes it to L1. The appchain
// account signs plays.
//
// Writes go through starknet.js (system calls + piltover). Reads come from
// Torii: model rows for current state, Dojo event-message tables for the
// per-mint / per-play / per-claim feeds. The one exception is the L1-side
// purchase log (piltover `MessageSent`), read straight from the settlement RPC
// so the "pending mint" state survives even before the appchain relays.

import { Account, type AccountInterface, RpcProvider, hash } from "starknet";
import { ToriiClient } from "@dojoengine/torii-wasm";
import deployments from "./deployments.json";

export const SETTLEMENT_RPC = deployments.settlement.rpcUrl;
export const APPCHAIN_RPC = deployments.appchain.rpcUrl;
export const SETTLEMENT_EXPLORER = deployments.settlement.explorer;
export const APPCHAIN_EXPLORER = deployments.appchain.explorer;

// Torii indexers (one per chain).
export const TORII_SCORE = deployments.settlement.torii; // settlement: score world
export const TORII_GAME = deployments.appchain.torii; // appchain: game world

export const PILTOVER = deployments.settlement.piltover;
export const SCORE_WORLD = deployments.settlement.scoreWorld;
export const STORE_WORLD = deployments.settlement.storeWorld;
export const GAME_WORLD = deployments.appchain.gameWorld;
// Dojo system contracts: the `game`/`score_registry` system addresses are what
// the frontend calls and what the cross-chain messages target.
export const GAME = deployments.appchain.gameSystem; // appchain game system
export const SCORE_REGISTRY = deployments.settlement.scoreSystem; // settlement score system
export const STORE = deployments.settlement.storeSystem; // settlement store system (buy_game)

export const BUYER_ADDRESS = deployments.settlement.account.address; // signs on L1
export const PLAYER_ADDRESS = deployments.appchain.account.address; // signs on L2

const MINT_GAME_SELECTOR = hash.getSelectorFromName("mint_game");
const MESSAGE_SENT_KEY = hash.getSelectorFromName("MessageSent"); // piltover core (L1)

const sameFelt = (a: string, b: string) => BigInt(a) === BigInt(b);
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
/** Torii returns felt/uint columns as hex strings; collapse to a JS number. */
const num = (v: string | number): number => (typeof v === "number" ? v : Number(BigInt(v)));

const settlementProvider = new RpcProvider({ nodeUrl: SETTLEMENT_RPC });
const appchainProvider = new RpcProvider({ nodeUrl: APPCHAIN_RPC });

// Dev keys printed by `katana --dev` / generated by `katana init rollup`.
// Throwaway local keys — never reuse with real funds. `settlementAccount` is the
// default L1 signer (buy/bank); the wallet layer can swap in a Controller account.
export const settlementAccount = new Account({
  provider: settlementProvider,
  address: deployments.settlement.account.address,
  signer: deployments.settlement.account.privateKey,
  cairoVersion: "1",
});
// Default L2 signer (roll). The wallet layer can swap in a Controller account.
export const appchainAccount = new Account({
  provider: appchainProvider,
  address: deployments.appchain.account.address,
  signer: deployments.appchain.account.privateKey,
  cairoVersion: "1",
});

/** Minimal signer interface — anything that can submit a tx (a starknet.js
 *  Account, or a Controller account wrapped to target a specific chain). */
export type Signer = Pick<AccountInterface, "execute">;

// Purchases and score-claims are both signed by the settlement account, so they
// must not race on the nonce. Serialize them through a promise-chain mutex.
let settlementQueue: Promise<unknown> = Promise.resolve();
function withSettlementLock<T>(fn: () => Promise<T>): Promise<T> {
  const run = settlementQueue.then(fn, fn);
  settlementQueue = run.then(
    () => {},
    () => {},
  );
  return run;
}

// --- Torii SQL ---

/** Run a read-only SQL query against a Torii instance; returns the JSON rows. */
async function toriiSql<T = Record<string, string | number>>(base: string, sql: string): Promise<T[]> {
  const res = await fetch(`${base}/sql?query=${encodeURIComponent(sql)}`);
  if (!res.ok) throw new Error(`torii sql ${res.status}: ${await res.text()}`);
  return (await res.json()) as T[];
}

// --- Per-service health ---

/** The independently-probeable network services (saya has no endpoint of its own
 *  — its health is inferred from settlement progress in the UI). */
export type ServiceId = "settlement" | "appchain" | "toriiScore" | "toriiGame";

/** Ping each service in parallel and report which are reachable. Each probe is
 *  isolated, so one service being down never hides the status of the others. */
export async function probeServices(): Promise<Record<ServiceId, boolean>> {
  const ok = async (p: Promise<unknown>): Promise<boolean> => {
    try {
      await p;
      return true;
    } catch {
      return false;
    }
  };
  const [settlement, appchain, toriiScore, toriiGame] = await Promise.all([
    ok(settlementProvider.getBlockNumber()),
    ok(appchainProvider.getBlockNumber()),
    ok(toriiSql(TORII_SCORE, "SELECT 1")),
    ok(toriiSql(TORII_GAME, "SELECT 1")),
  ]);
  return { settlement, appchain, toriiScore, toriiGame };
}

// --- Torii subscriptions (gRPC) ---

/** Subscribe to live updates from both Torii worlds and call `onUpdate` whenever
 *  something changes — a model is set (`game-Stats`, `score-Leaderboard`) or an
 *  event is emitted (`GameMinted` / `GamePlayed` / `ScoreClaimed`). This replaces
 *  fixed-interval Torii polling: the UI refetches only when there's actually new
 *  data. We pass a `null` clause to each subscription (every entity/event in the
 *  world) and ignore the payload — the caller re-reads via the typed SQL helpers,
 *  which keep the cross-table joins (play↔claim, mint↔message) in one place.
 *
 *  Returns an async cleanup that cancels the subscriptions. If a client can't
 *  connect, it throws — the caller keeps a slow poll as a safety net (and for the
 *  RPC-only reads, which have no Torii subscription). */
export async function subscribeToriiUpdates(onUpdate: () => void): Promise<() => void> {
  const subs: { cancel: () => void }[] = [];
  const clients: ToriiClient[] = [];

  const connect = async (toriiUrl: string, worldAddress: string) => {
    // NB: despite its `.d.ts`, the wasm `ToriiClient` constructor is async — it
    // returns a Promise that resolves to the connected client, so it's awaited.
    const client = await (new ToriiClient({ toriiUrl, worldAddress }) as unknown as Promise<ToriiClient>);
    clients.push(client);
    // Models are entities; the per-action feeds are event messages — watch both.
    subs.push(await client.onEntityUpdated(null, null, () => onUpdate()));
    subs.push(await client.onEventMessageUpdated(null, null, () => onUpdate()));
  };

  await Promise.all([connect(TORII_GAME, GAME_WORLD), connect(TORII_SCORE, SCORE_WORLD)]);

  return () => {
    for (const s of subs) {
      try {
        s.cancel();
      } catch {
        // already gone — fine
      }
    }
    for (const c of clients) {
      try {
        c.free();
      } catch {
        // already freed — fine
      }
    }
  };
}

/** Torii stamps each event-message row with `internal_event_id` formatted as
 *  `<block>:<txHash>:<world>:<idx>`. Pull out the block and L2 tx hash. */
function parseEventId(internalEventId: string): { block: number; txHash: string } {
  const [blockHex, txHash] = internalEventId.split(":");
  return { block: num(blockHex), txHash };
}

export function explorerTxUrl(explorerBase: string, txHash: string): string {
  return `${explorerBase}/tx/${txHash}`;
}

export function explorerAddrUrl(explorerBase: string, address: string): string {
  return `${explorerBase}/contract/${address}`;
}

export function shortHex(value: string, lead = 6, tail = 4): string {
  if (!value) return "—";
  if (value.length <= lead + tail + 2) return value;
  return `${value.slice(0, lead)}…${value.slice(-tail)}`;
}

// --- Appchain game state (game world `Stats` model) ---

export type GameState = {
  totalMinted: number; // games purchased
  available: number; // minted, not yet played
  totalPlayed: number;
  lastScore: number;
};

export async function readGameState(): Promise<GameState> {
  const rows = await toriiSql(TORII_GAME, 'SELECT total_minted, available, total_played, last_score FROM "game-Stats" WHERE id = 0');
  const r = rows[0];
  if (!r) return { totalMinted: 0, available: 0, totalPlayed: 0, lastScore: 0 };
  return {
    totalMinted: num(r.total_minted),
    available: num(r.available),
    totalPlayed: num(r.total_played),
    lastScore: num(r.last_score),
  };
}

/** Per-player playable-credit balances (game world `Credits` model), keyed by the
 *  normalized (value-compared) player address. A buy credits the player; a roll
 *  spends one. Look up a connected player's balance with the normalized address. */
export async function readCredits(): Promise<Map<string, number>> {
  const rows = await toriiSql<{ player: string; balance: string | number }>(
    TORII_GAME,
    'SELECT player, balance FROM "game-Credits"',
  );
  const m = new Map<string, number>();
  for (const r of rows) m.set(BigInt(r.player).toString(), num(r.balance));
  return m;
}

// --- L1 published-score state (score world `Leaderboard` model) ---

export type ScoreState = { lastPublished: number; totalPublished: number };

export async function readScoreState(): Promise<ScoreState> {
  const rows = await toriiSql(TORII_SCORE, 'SELECT last_score, total FROM "score-Leaderboard" WHERE id = 0');
  const r = rows[0];
  if (!r) return { lastPublished: 0, totalPublished: 0 };
  return { lastPublished: num(r.last_score), totalPublished: num(r.total) };
}

// --- Phase 1: purchase (L1 -> L2) ---

/** L1 op: buy a game through the store contract, which runs the store's rules
 *  and then sends the L1 -> L2 message (via the piltover core) that mints a
 *  credit on L2. The client calls the game's own contract, not piltover directly. */
export async function purchaseGame(account: Signer, player: string, gameId: number): Promise<string> {
  return withSettlementLock(async () => {
    const { transaction_hash } = await account.execute({
      contractAddress: STORE,
      entrypoint: "buy_game",
      // buy_game(player, game_id): `player` is the L2 address to credit (the L1
      // buyer and the L2 player can differ — dev uses two keys, Controller one).
      calldata: [player, "0x" + gameId.toString(16)],
    });
    return transaction_hash;
  });
}

type RawEvent = { transaction_hash: string; keys: string[]; data: string[] };

/** Fetch all events for an address + key from an RPC, oldest-first, paginated. */
async function fetchEvents(p: RpcProvider, address: string, key: string): Promise<RawEvent[]> {
  const out: RawEvent[] = [];
  let continuationToken: string | undefined;
  for (let page = 0; page < 50; page++) {
    const res = await p.getEvents({
      address,
      from_block: { block_number: 0 },
      to_block: "latest",
      keys: [[key]],
      chunk_size: 100,
      continuation_token: continuationToken,
    });
    for (const ev of res.events) out.push({ transaction_hash: ev.transaction_hash, keys: ev.keys, data: ev.data });
    continuationToken = res.continuation_token;
    if (!continuationToken) break;
  }
  return out;
}

// Event-sourced history so the feeds survive a page refresh.

export type PurchaseRecord = {
  seq: number; // 1-based order
  l1TxHash: string; // send_message_to_appchain tx on the settlement layer
  mintTxHash?: string; // relayed mint_game tx on the appchain (once minted)
};

/** Rebuild the purchase list: each L1 `MessageSent` (to the game system, with
 *  the `mint_game` selector) is a purchase; the matching `GameMinted` event in
 *  the game world (same FIFO order) is its relayed mint. */
export async function getPurchaseHistory(): Promise<PurchaseRecord[]> {
  const [sent, minted] = await Promise.all([
    fetchEvents(settlementProvider, PILTOVER, MESSAGE_SENT_KEY),
    toriiSql<{ mint_no: number; internal_event_id: string }>(
      TORII_GAME,
      'SELECT mint_no, internal_event_id FROM "game-GameMinted" ORDER BY mint_no',
    ),
  ]);
  // MessageSent: keys=[selector, message_hash, from, to], data=[selector, nonce, payload_len, ...payload]
  const purchases = sent.filter(
    (e) => e.keys.length >= 4 && sameFelt(e.keys[3], GAME) && sameFelt(e.data[0], MINT_GAME_SELECTOR),
  );
  return purchases.map((e, i) => ({
    seq: i + 1,
    l1TxHash: e.transaction_hash,
    mintTxHash: minted[i] ? parseEventId(minted[i].internal_event_id).txHash : undefined,
  }));
}

export type PlayRecord = {
  seq: number;
  player: string; // who rolled (GamePlayed.player) — the address claim_score must consume for
  score: number;
  block: number; // appchain block the play landed in (gates settling on saya)
  l2TxHash: string; // play_game tx on the appchain
  claimTxHash?: string; // claim_score (settle) tx on the settlement layer, once published
};

/** Rebuild the play list: each `GamePlayed` event (game world) is a play; the
 *  matching `ScoreClaimed` event (score world) is its publish to L1. Claims are
 *  matched by score (first-come) so a game settled out of order still lines up
 *  with its own tx. */
export async function getPlayHistory(): Promise<PlayRecord[]> {
  const [played, claimed] = await Promise.all([
    toriiSql<{ game_no: number; player: string; score: string | number; internal_event_id: string }>(
      TORII_GAME,
      'SELECT game_no, player, score, internal_event_id FROM "game-GamePlayed" ORDER BY game_no',
    ),
    toriiSql<{ claim_no: number; player: string; score: string | number; internal_event_id: string }>(
      TORII_SCORE,
      'SELECT claim_no, player, score, internal_event_id FROM "score-ScoreClaimed" ORDER BY claim_no',
    ),
  ]);
  // Match a claim to its play by (player, score) so banks line up per-roller even
  // when two players roll the same score. Normalize the player address (Torii pads
  // it) so the keys compare equal regardless of leading zeros.
  const norm = (a: string) => BigInt(a).toString();
  const claimsByKey = new Map<string, string[]>();
  for (const c of claimed) {
    const key = `${norm(c.player)}:${num(c.score)}`;
    const tx = parseEventId(c.internal_event_id).txHash;
    const q = claimsByKey.get(key);
    if (q) q.push(tx);
    else claimsByKey.set(key, [tx]);
  }
  return played.map((e, i) => {
    const score = num(e.score);
    const { block, txHash } = parseEventId(e.internal_event_id);
    const q = claimsByKey.get(`${norm(e.player)}:${score}`);
    const claimTxHash = q && q.length ? q.shift() : undefined;
    return { seq: i + 1, player: e.player, score, block, l2TxHash: txHash, claimTxHash };
  });
}

// --- Phase 2 + 3: play (rolls + publishes to L1 in one tx) ---

/** Play one available game. Rolls on chain and emits the score to L1. Returns
 *  the L2 tx hash, the block it landed in, and the rolled score (read back from
 *  the game world's `Stats` once Torii has indexed the play). */
export async function playGame(account: Signer): Promise<{ txHash: string; block: number; score: number }> {
  const before = await readGameState();
  const { transaction_hash } = await account.execute({
    contractAddress: GAME,
    entrypoint: "play_game",
    calldata: [],
  });
  await appchainProvider.waitForTransaction(transaction_hash);
  const block = await appchainProvider.getBlockNumber();
  // Wait for Torii to index the play so the rolled score is readable.
  let score = before.lastScore;
  for (let i = 0; i < 60; i++) {
    const s = await readGameState();
    if (s.totalPlayed > before.totalPlayed) {
      score = s.lastScore;
      break;
    }
    await sleep(150);
  }
  return { txHash: transaction_hash, block, score };
}

/** Current appchain block height. */
export async function appchainBlock(): Promise<number> {
  return appchainProvider.getBlockNumber();
}

/** Block height settled onto the piltover core by saya (get_state()[1]). */
export async function settledBlock(): Promise<number> {
  const res = await settlementProvider.callContract({
    contractAddress: PILTOVER,
    entrypoint: "get_state",
    calldata: [],
  });
  const bn = BigInt(res[1]);
  return bn > 0xffffffffffffffffn ? -1 : Number(bn);
}

/** L1 op: consume the settled score on the settlement layer (banking a run). */
export async function claimScore(
  account: Signer,
  player: string,
  score: number,
): Promise<string> {
  return withSettlementLock(async () => {
    const { transaction_hash } = await account.execute({
      contractAddress: SCORE_REGISTRY,
      entrypoint: "claim_score",
      // claim_score(from_address = game system, player, score)
      calldata: [GAME, player, "0x" + score.toString(16)],
    });
    await settlementProvider.waitForTransaction(transaction_hash);
    return transaction_hash;
  });
}
