// Frontend data layer for the cross-chain game (Dojo + Torii edition).
//
// Settlement ("L1"): piltover core + the `score` Dojo world (score_registry
// system). The settlement account signs purchases (L1->L2) and score claims.
// Appchain ("L2"): the `game` Dojo world (game system) — purchase mints a
// playable game, play rolls a score and publishes it to L1. The appchain
// account signs plays.
//
// Writes go through starknet.js (system calls + piltover). Reads come from
// Torii: model rows for current state, Dojo event-message tables for the
// per-mint / per-play / per-claim feeds. The one exception is the L1-side
// purchase log (piltover `MessageSent`), read straight from the settlement RPC
// so the "pending mint" state survives even before the appchain relays.

import { Account, RpcProvider, hash } from "starknet";
import deployments from "./deployments.json";

export const SETTLEMENT_RPC = deployments.settlement.rpcUrl;
export const APPCHAIN_RPC = deployments.appchain.rpcUrl;
export const SETTLEMENT_EXPLORER = deployments.settlement.explorer;
export const APPCHAIN_EXPLORER = deployments.appchain.explorer;

// Torii indexers (one per chain).
export const TORII_SCORE = deployments.settlement.torii; // settlement: score world
export const TORII_GAME = deployments.appchain.torii; // appchain: game world

export const PILTOVER = deployments.settlement.piltover;
export const SCORE_WORLD = deployments.settlement.scoreWorld;
export const GAME_WORLD = deployments.appchain.gameWorld;
// Dojo system contracts: the `game`/`score_registry` system addresses are what
// the frontend calls and what the cross-chain messages target.
export const GAME = deployments.appchain.gameSystem; // appchain game system
export const SCORE_REGISTRY = deployments.settlement.scoreSystem; // settlement score system

export const BUYER_ADDRESS = deployments.settlement.account.address; // signs on L1
export const PLAYER_ADDRESS = deployments.appchain.account.address; // signs on L2

const MINT_GAME_SELECTOR = hash.getSelectorFromName("mint_game");
const MESSAGE_SENT_KEY = hash.getSelectorFromName("MessageSent"); // piltover core (L1)

const sameFelt = (a: string, b: string) => BigInt(a) === BigInt(b);
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
/** Torii returns felt/uint columns as hex strings; collapse to a JS number. */
const num = (v: string | number): number => (typeof v === "number" ? v : Number(BigInt(v)));

const settlementProvider = new RpcProvider({ nodeUrl: SETTLEMENT_RPC });
const appchainProvider = new RpcProvider({ nodeUrl: APPCHAIN_RPC });

// Dev keys printed by `katana --dev` / generated by `katana init rollup`.
// Throwaway local keys — never reuse with real funds.
const settlementAccount = new Account({
  provider: settlementProvider,
  address: deployments.settlement.account.address,
  signer: deployments.settlement.account.privateKey,
  cairoVersion: "1",
});
const appchainAccount = new Account({
  provider: appchainProvider,
  address: deployments.appchain.account.address,
  signer: deployments.appchain.account.privateKey,
  cairoVersion: "1",
});

// Purchases and score-claims are both signed by the settlement account, so they
// must not race on the nonce. Serialize them through a promise-chain mutex.
let settlementQueue: Promise<unknown> = Promise.resolve();
function withSettlementLock<T>(fn: () => Promise<T>): Promise<T> {
  const run = settlementQueue.then(fn, fn);
  settlementQueue = run.then(
    () => {},
    () => {},
  );
  return run;
}

// --- Torii SQL ---

/** Run a read-only SQL query against a Torii instance; returns the JSON rows. */
async function toriiSql<T = Record<string, string | number>>(base: string, sql: string): Promise<T[]> {
  const res = await fetch(`${base}/sql?query=${encodeURIComponent(sql)}`);
  if (!res.ok) throw new Error(`torii sql ${res.status}: ${await res.text()}`);
  return (await res.json()) as T[];
}

/** Torii stamps each event-message row with `internal_event_id` formatted as
 *  `<block>:<txHash>:<world>:<idx>`. Pull out the block and L2 tx hash. */
function parseEventId(internalEventId: string): { block: number; txHash: string } {
  const [blockHex, txHash] = internalEventId.split(":");
  return { block: num(blockHex), txHash };
}

export function explorerTxUrl(explorerBase: string, txHash: string): string {
  return `${explorerBase}/tx/${txHash}`;
}

export function explorerAddrUrl(explorerBase: string, address: string): string {
  return `${explorerBase}/contract/${address}`;
}

export function shortHex(value: string, lead = 6, tail = 4): string {
  if (!value) return "—";
  if (value.length <= lead + tail + 2) return value;
  return `${value.slice(0, lead)}…${value.slice(-tail)}`;
}

// --- Appchain game state (game world `Stats` model) ---

export type GameState = {
  totalMinted: number; // games purchased
  available: number; // minted, not yet played
  totalPlayed: number;
  lastScore: number;
};

export async function readGameState(): Promise<GameState> {
  const rows = await toriiSql(TORII_GAME, 'SELECT total_minted, available, total_played, last_score FROM "game-Stats" WHERE id = 0');
  const r = rows[0];
  if (!r) return { totalMinted: 0, available: 0, totalPlayed: 0, lastScore: 0 };
  return {
    totalMinted: num(r.total_minted),
    available: num(r.available),
    totalPlayed: num(r.total_played),
    lastScore: num(r.last_score),
  };
}

// --- L1 published-score state (score world `Leaderboard` model) ---

export type ScoreState = { lastPublished: number; totalPublished: number };

export async function readScoreState(): Promise<ScoreState> {
  const rows = await toriiSql(TORII_SCORE, 'SELECT last_score, total FROM "score-Leaderboard" WHERE id = 0');
  const r = rows[0];
  if (!r) return { lastPublished: 0, totalPublished: 0 };
  return { lastPublished: num(r.last_score), totalPublished: num(r.total) };
}

// --- Phase 1: purchase (L1 -> L2) ---

/** L1 op: send a message via the piltover core to mint a playable game on L2. */
export async function purchaseGame(gameId: number): Promise<string> {
  return withSettlementLock(async () => {
    const { transaction_hash } = await settlementAccount.execute({
      contractAddress: PILTOVER,
      entrypoint: "send_message_to_appchain",
      calldata: [GAME, MINT_GAME_SELECTOR, "1", "0x" + gameId.toString(16)],
    });
    return transaction_hash;
  });
}

type RawEvent = { transaction_hash: string; keys: string[]; data: string[] };

/** Fetch all events for an address + key from an RPC, oldest-first, paginated. */
async function fetchEvents(p: RpcProvider, address: string, key: string): Promise<RawEvent[]> {
  const out: RawEvent[] = [];
  let continuationToken: string | undefined;
  for (let page = 0; page < 50; page++) {
    const res = await p.getEvents({
      address,
      from_block: { block_number: 0 },
      to_block: "latest",
      keys: [[key]],
      chunk_size: 100,
      continuation_token: continuationToken,
    });
    for (const ev of res.events) out.push({ transaction_hash: ev.transaction_hash, keys: ev.keys, data: ev.data });
    continuationToken = res.continuation_token;
    if (!continuationToken) break;
  }
  return out;
}

// Event-sourced history so the feeds survive a page refresh.

export type PurchaseRecord = {
  seq: number; // 1-based order
  l1TxHash: string; // send_message_to_appchain tx on the settlement layer
  mintTxHash?: string; // relayed mint_game tx on the appchain (once minted)
};

/** Rebuild the purchase list: each L1 `MessageSent` (to the game system, with
 *  the `mint_game` selector) is a purchase; the matching `GameMinted` event in
 *  the game world (same FIFO order) is its relayed mint. */
export async function getPurchaseHistory(): Promise<PurchaseRecord[]> {
  const [sent, minted] = await Promise.all([
    fetchEvents(settlementProvider, PILTOVER, MESSAGE_SENT_KEY),
    toriiSql<{ mint_no: number; internal_event_id: string }>(
      TORII_GAME,
      'SELECT mint_no, internal_event_id FROM "game-GameMinted" ORDER BY mint_no',
    ),
  ]);
  // MessageSent: keys=[selector, message_hash, from, to], data=[selector, nonce, payload_len, ...payload]
  const purchases = sent.filter(
    (e) => e.keys.length >= 4 && sameFelt(e.keys[3], GAME) && sameFelt(e.data[0], MINT_GAME_SELECTOR),
  );
  return purchases.map((e, i) => ({
    seq: i + 1,
    l1TxHash: e.transaction_hash,
    mintTxHash: minted[i] ? parseEventId(minted[i].internal_event_id).txHash : undefined,
  }));
}

export type PlayRecord = {
  seq: number;
  score: number;
  block: number; // appchain block the play landed in (gates settling on saya)
  l2TxHash: string; // play_game tx on the appchain
  claimTxHash?: string; // claim_score (settle) tx on the settlement layer, once published
};

/** Rebuild the play list: each `GamePlayed` event (game world) is a play; the
 *  matching `ScoreClaimed` event (score world) is its publish to L1. Claims are
 *  matched by score (first-come) so a game settled out of order still lines up
 *  with its own tx. */
export async function getPlayHistory(): Promise<PlayRecord[]> {
  const [played, claimed] = await Promise.all([
    toriiSql<{ game_no: number; score: string | number; internal_event_id: string }>(
      TORII_GAME,
      'SELECT game_no, score, internal_event_id FROM "game-GamePlayed" ORDER BY game_no',
    ),
    toriiSql<{ claim_no: number; score: string | number; internal_event_id: string }>(
      TORII_SCORE,
      'SELECT claim_no, score, internal_event_id FROM "score-ScoreClaimed" ORDER BY claim_no',
    ),
  ]);
  const claimsByScore = new Map<number, string[]>();
  for (const c of claimed) {
    const sc = num(c.score);
    const tx = parseEventId(c.internal_event_id).txHash;
    const q = claimsByScore.get(sc);
    if (q) q.push(tx);
    else claimsByScore.set(sc, [tx]);
  }
  return played.map((e, i) => {
    const score = num(e.score);
    const { block, txHash } = parseEventId(e.internal_event_id);
    const q = claimsByScore.get(score);
    const claimTxHash = q && q.length ? q.shift() : undefined;
    return { seq: i + 1, score, block, l2TxHash: txHash, claimTxHash };
  });
}

// --- Phase 2 + 3: play (rolls + publishes to L1 in one tx) ---

/** Play one available game. Rolls on chain and emits the score to L1. Returns
 *  the L2 tx hash, the block it landed in, and the rolled score (read back from
 *  the game world's `Stats` once Torii has indexed the play). */
export async function playGame(): Promise<{ txHash: string; block: number; score: number }> {
  const before = await readGameState();
  const { transaction_hash } = await appchainAccount.execute({
    contractAddress: GAME,
    entrypoint: "play_game",
    calldata: [],
  });
  await appchainProvider.waitForTransaction(transaction_hash);
  const block = await appchainProvider.getBlockNumber();
  // Wait for Torii to index the play so the rolled score is readable.
  let score = before.lastScore;
  for (let i = 0; i < 60; i++) {
    const s = await readGameState();
    if (s.totalPlayed > before.totalPlayed) {
      score = s.lastScore;
      break;
    }
    await sleep(150);
  }
  return { txHash: transaction_hash, block, score };
}

/** Current appchain block height. */
export async function appchainBlock(): Promise<number> {
  return appchainProvider.getBlockNumber();
}

/** Block height settled onto the piltover core by saya (get_state()[1]). */
export async function settledBlock(): Promise<number> {
  const res = await settlementProvider.callContract({
    contractAddress: PILTOVER,
    entrypoint: "get_state",
    calldata: [],
  });
  const bn = BigInt(res[1]);
  return bn > 0xffffffffffffffffn ? -1 : Number(bn);
}

/** L1 op: consume the settled score on the settlement layer (banking a run). */
export async function claimScore(player: string, score: number): Promise<string> {
  return withSettlementLock(async () => {
    const { transaction_hash } = await settlementAccount.execute({
      contractAddress: SCORE_REGISTRY,
      entrypoint: "claim_score",
      // claim_score(from_address = game system, player, score)
      calldata: [GAME, player, "0x" + score.toString(16)],
    });
    await settlementProvider.waitForTransaction(transaction_hash);
    return transaction_hash;
  });
}
