[package]
edition.workspace = true
license.workspace = true
name = "katana-node-cli"
repository.workspace = true
version.workspace = true

[dependencies]
katana-chain-spec.workspace = true
katana-core.workspace = true
katana-messaging.workspace = true
katana-node.workspace = true
katana-node-cli-args = { workspace = true, features = [ "cartridge", "server" ] }
katana-primitives.workspace = true
katana-slot-controller = { workspace = true, optional = true }
katana-tracing.workspace = true
katana-utils.workspace = true
serde-utils.workspace = true

alloy-primitives.workspace = true
anyhow.workspace = true
clap.workspace = true
console.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
assert_matches.workspace = true
katana-gas-price-oracle.workspace = true
starknet.workspace = true

[features]
cartridge = [ "dep:katana-slot-controller", "katana-node/cartridge" ]
default = [ "cartridge", "server" ]
explorer = [ "katana-node-cli-args/explorer", "katana-node/explorer" ]
native = [ "katana-node-cli-args/native", "katana-node/native" ]
server = [  ]
