// Shared helpers for the cross-chain-dungeon deploy step.
//
// Two kinds of deploys:
//   - Dojo worlds (score on Sepolia, game on the appchain) via `sozo migrate`.
//   - Plain Starknet contracts (GAME_TOKEN, TokenSale, Entry) via starknet.js
//     declareAndDeploy, since they aren't Dojo worlds.
//
// Settlement is REAL Starknet Sepolia; the appchain is a local Katana rollup.

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Account, RpcProvider, hash, type Calldata } from "starknet";

const __dirname = dirname(fileURLToPath(import.meta.url));

export const DEMO_ROOT = resolve(__dirname, "..");
export const CAIRO_DIR = resolve(DEMO_ROOT, "cairo");
export const DEPLOYMENTS_PATH = resolve(DEMO_ROOT, "app/src/deployments.json");

export type Keypair = { address: string; privateKey: string };

export type Deployments = {
  settlement: {
    rpcUrl: string;
    explorer: string;
    torii: string;
    account: Keypair; // operator (deployer / migrator)
    piltover: string;
    usdc: string;
    gameToken?: string;
    goldToken?: string;
    tokenSale?: string;
    entry?: string;
    bankWorld?: string;
    bankSystem?: string;
  };
  appchain: {
    rpcUrl: string;
    explorer: string;
    torii: string;
    account: Keypair; // appchain dev account (from the rollup genesis)
    gameWorld?: string;
    gameSystem?: string;
  };
};

export function loadJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf-8")) as T;
}

export function loadDeployments(): Deployments {
  return loadJson<Deployments>(DEPLOYMENTS_PATH);
}

export function saveDeployments(d: Deployments): void {
  writeFileSync(DEPLOYMENTS_PATH, JSON.stringify(d, null, 2) + "\n");
}

// ---- Dojo world migration (sozo) ----

export type MigrateSpec = {
  /** Package directory under cairo/ (e.g. "game" or "score"). */
  pkg: string;
  /** Deterministic world seed (stable address across re-migrations). */
  seed: string;
  /** Dojo namespace for this world's resources. */
  namespace: string;
  /** Contract tag granted writer permission + initialized (e.g. "game-game"). */
  systemTag: string;
  /** Chain to migrate against. */
  rpcUrl: string;
  account: Keypair;
  /** dojo_init calldata for `systemTag` (felt hex strings; u256 = low, high). */
  initArgs: string[];
};

function renderDojoToml(s: MigrateSpec): string {
  const args = s.initArgs.map((a) => `"${a}"`).join(", ");
  return `# Generated by scripts/deploy.ts — do not edit (regenerated each run).
[world]
name = "cross_chain_dungeon"
seed = "${s.seed}"

[namespace]
default = "${s.namespace}"

[env]
rpc_url = "${s.rpcUrl}"
account_address = "${s.account.address}"
private_key = "${s.account.privateKey}"

[writers]
"${s.namespace}" = ["${s.systemTag}"]

[init_call_args]
"${s.systemTag}" = [${args}]
`;
}

type Manifest = { world: { address: string }; contracts: { tag: string; address: string }[] };

/** Build + migrate one world; returns its world address and system address. */
export function migrateWorld(s: MigrateSpec): { world: string; system: string } {
  const cwd = resolve(CAIRO_DIR, s.pkg);
  writeFileSync(resolve(cwd, "dojo_dev.toml"), renderDojoToml(s));

  const run = (args: string[]) =>
    execFileSync("sozo", args, { cwd, stdio: ["ignore", "inherit", "inherit"] });
  run(["build"]);
  run(["migrate"]);

  const manifest = loadJson<Manifest>(resolve(cwd, "manifest_dev.json"));
  const contract = manifest.contracts.find((c) => c.tag === s.systemTag);
  if (!contract) throw new Error(`system ${s.systemTag} not found in ${s.pkg} manifest`);
  return { world: manifest.world.address, system: contract.address };
}

// ---- plain Starknet contract deploy (starknet.js) ----

export function provider(rpcUrl: string): RpcProvider {
  return new RpcProvider({ nodeUrl: rpcUrl });
}

export function account(rpcUrl: string, kp: Keypair): Account {
  return new Account({ provider: provider(rpcUrl), address: kp.address, signer: kp.privateKey, cairoVersion: "1" });
}

/** `scarb build` a plain (non-Dojo) contract package so its artifacts exist. */
export function buildPackage(pkg: string): void {
  execFileSync("scarb", ["build"], {
    cwd: resolve(CAIRO_DIR, pkg),
    stdio: ["ignore", "inherit", "inherit"],
  });
}

/** The scarb package name (artifacts are prefixed with it, not the dir name). */
function packageName(pkg: string): string {
  const toml = readFileSync(resolve(CAIRO_DIR, pkg, "Scarb.toml"), "utf-8");
  const m = toml.match(/name\s*=\s*"([^"]+)"/);
  return m ? m[1] : pkg;
}

/** Read the sierra + casm artifacts scarb emitted for a contract module. */
function artifacts(pkg: string, contract: string): { sierra: unknown; casm: unknown } {
  const base = resolve(CAIRO_DIR, pkg, "target/dev", `${packageName(pkg)}_${contract}`);
  return {
    sierra: loadJson(`${base}.contract_class.json`),
    casm: loadJson(`${base}.compiled_contract_class.json`),
  };
}

/**
 * Declare (if needed) and deploy a plain Starknet contract, returning its address.
 * `constructorCalldata` is compiled against the contract's ABI by starknet.js.
 */
export async function declareAndDeploy(
  acc: Account,
  pkg: string,
  contract: string,
  constructorCalldata: Calldata | Record<string, unknown>,
): Promise<string> {
  const { sierra, casm } = artifacts(pkg, contract);
  // Starknet >= 0.14.1 (Sepolia/mainnet) computes the compiled-class hash with
  // Blake2s, not Poseidon. starknet.js 10.x's
  // computeCompiledClassHash is Blake2s — compute it and pass it explicitly so
  // the declare's compiled_class_hash matches what the sequencer derives.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const compiledClassHash = hash.computeCompiledClassHash(casm as any);
  const res = await acc.declareAndDeploy({
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    contract: sierra as any,
    compiledClassHash,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    constructorCalldata: constructorCalldata as any,
  });
  return res.deploy.contract_address;
}

/** Invoke an entrypoint and wait for it to be accepted. */
export async function invoke(
  acc: Account,
  contractAddress: string,
  entrypoint: string,
  calldata: Calldata,
): Promise<void> {
  const { transaction_hash } = await acc.execute({ contractAddress, entrypoint, calldata });
  // starknet.js 10.x moved waitForTransaction off Account onto the provider.
  await acc.provider.waitForTransaction(transaction_hash);
}

export async function waitForRpc(rpcUrl: string, timeoutMs = 30_000): Promise<void> {
  const start = Date.now();
  const body = JSON.stringify({ jsonrpc: "2.0", id: 1, method: "starknet_chainId", params: [] });
  for (;;) {
    try {
      const res = await fetch(rpcUrl, { method: "POST", headers: { "content-type": "application/json" }, body });
      if (res.ok) return;
    } catch {
      // not up yet
    }
    if (Date.now() - start > timeoutMs) throw new Error(`RPC ${rpcUrl} not up in ${timeoutMs}ms`);
    await new Promise((r) => setTimeout(r, 500));
  }
}
