[package]
description = "Katana database integrity verification tool"
edition.workspace = true
license.workspace = true
name = "katana-verifier"
repository.workspace = true
version.workspace = true

[dependencies]
# Core dependencies
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true

# Katana dependencies
katana-db.workspace = true
katana-executor.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true
katana-trie.workspace = true

# Serialization
serde = { workspace = true, features = [ "derive" ] }
serde_json.workspace = true

# CLI (only for binary)
clap = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }

# Hash and crypto
starknet-types-core.workspace = true

[dev-dependencies]
# Test utilities
rstest.workspace = true
tempfile.workspace = true

# Katana test utilities
katana-executor.workspace = true

[[bin]]
name = "katana-verifier"
path = "src/bin/main.rs"
required-features = [ "cli" ]

[features]
cli = [ "clap", "tracing-subscriber" ]
