[package]
name = "katana_account"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet.workspace = true
openzeppelin_account.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_upgrades.workspace = true

[[target.starknet-contract]]
sierra = true
casm = true
