// Shared helpers for the cross-chain game deploy step (Dojo edition).
//
// The unified demo runs a settlement Katana ("L1", SN_SEPOLIA) and a rollup
// appchain Katana ("L2") that settles to a piltover core via its embedded
// settlement service. `up.sh`
// deploys the piltover core (via `katana init rollup`) and writes the base
// `deployments.json` (rpc urls, accounts, piltover, torii urls).
//
// This deploy step migrates two Dojo worlds with `sozo`:
//   - score world  (namespace "score")  on the settlement layer
//   - game world   (namespace "game")   on the appchain
// and records each world + system address back into `deployments.json`.

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

export const DEMO_ROOT = resolve(__dirname, "..");
export const CAIRO_DIR = resolve(DEMO_ROOT, "cairo");
export const DEPLOYMENTS_PATH = resolve(DEMO_ROOT, "app/src/deployments.json");

export type Keypair = { address: string; privateKey: string };
export type Deployments = {
  settlement: {
    rpcUrl: string;
    explorer: string;
    torii: string;
    account: Keypair;
    piltover: string;
    scoreWorld?: string;
    scoreSystem?: string;
    storeWorld?: string;
    storeSystem?: string;
  };
  appchain: {
    rpcUrl: string;
    explorer: string;
    torii: string;
    account: Keypair;
    gameWorld?: string;
    gameSystem?: string;
  };
};

export function loadJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf-8")) as T;
}

export function loadDeployments(): Deployments {
  return loadJson<Deployments>(DEPLOYMENTS_PATH);
}

export function saveDeployments(d: Deployments): void {
  writeFileSync(DEPLOYMENTS_PATH, JSON.stringify(d, null, 2) + "\n");
}

/** A `sozo migrate` profile: which package dir, world, namespace, env, init. */
export type MigrateSpec = {
  /** Package directory under cairo/ (e.g. "game" or "score"). */
  pkg: string;
  /** Deterministic world seed (stable address across re-migrations). */
  seed: string;
  /** Dojo namespace for this world's resources. */
  namespace: string;
  /** Contract tag granted writer permission + initialized (e.g. "game-game"). */
  systemTag: string;
  /** Chain to migrate against. */
  rpcUrl: string;
  account: Keypair;
  /** dojo_init calldata for `systemTag` (felt hex strings). */
  initArgs: string[];
};

/** Render the `dojo_dev.toml` that `sozo migrate` reads (default profile). */
function renderDojoToml(s: MigrateSpec): string {
  const args = s.initArgs.map((a) => `"${a}"`).join(", ");
  return `# Generated by scripts/deploy.ts — do not edit (regenerated each run).
[world]
name = "cross_chain_game"
seed = "${s.seed}"

[namespace]
default = "${s.namespace}"

[env]
rpc_url = "${s.rpcUrl}"
account_address = "${s.account.address}"
private_key = "${s.account.privateKey}"

[writers]
"${s.namespace}" = ["${s.systemTag}"]

[init_call_args]
"${s.systemTag}" = [${args}]
`;
}

type Manifest = {
  world: { address: string };
  contracts: { tag: string; address: string }[];
};

/** Build + migrate one world; returns its world address and system address. */
export function migrateWorld(s: MigrateSpec): { world: string; system: string } {
  const cwd = resolve(CAIRO_DIR, s.pkg);
  writeFileSync(resolve(cwd, "dojo_dev.toml"), renderDojoToml(s));

  const run = (args: string[]) =>
    execFileSync("sozo", args, { cwd, stdio: ["ignore", "inherit", "inherit"] });
  run(["build"]);
  run(["migrate"]);

  const manifest = loadJson<Manifest>(resolve(cwd, "manifest_dev.json"));
  const contract = manifest.contracts.find((c) => c.tag === s.systemTag);
  if (!contract) throw new Error(`system ${s.systemTag} not found in ${s.pkg} manifest`);
  return { world: manifest.world.address, system: contract.address };
}

export async function waitForRpc(rpcUrl: string, timeoutMs = 30_000): Promise<void> {
  const start = Date.now();
  const body = JSON.stringify({ jsonrpc: "2.0", id: 1, method: "starknet_chainId", params: [] });
  for (;;) {
    try {
      const res = await fetch(rpcUrl, { method: "POST", headers: { "content-type": "application/json" }, body });
      if (res.ok) return;
    } catch {
      // not up yet
    }
    if (Date.now() - start > timeoutMs) throw new Error(`RPC ${rpcUrl} not up in ${timeoutMs}ms`);
    await new Promise((r) => setTimeout(r, 500));
  }
}
