//! Unit tests for verify_katana_report_data function.
//!
//! These test vectors were generated by:
//! cargo test -p katana_tee_client --test generate_report_data_vectors -- --nocapture

use core::integer::u512;
use katana_tee::katana_report_utils::verify_katana_report_data;

/// Test case 1: Large values
/// state_root: 0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
/// block_hash: 0x00fedcba9876543210fedcba9876543210fedcba9876543210fedcba98765432
/// commitment (poseidon_hash): 0x0707ec0977a29e3a54c6032ec5514d6188d75930d6d6eeb096cf4ca323df4aac
#[test]
fn test_verify_katana_report_data_case_1() {
    let report_data = u512 {
        limb0: 0x614d51c52e03c6543a9ea27709ec0707,
        limb1: 0xac4adf23a34ccf96b0eed6d63059d788,
        limb2: 0,
        limb3: 0,
    };

    let state_root: felt252 = 0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef;
    let block_hash: felt252 = 0x00fedcba9876543210fedcba9876543210fedcba9876543210fedcba98765432;

    let result = verify_katana_report_data(report_data, state_root, block_hash);
    assert(result, 'Verification should pass');
}

/// Test case 2: Small values
/// state_root: 0x0000000000000000000000000000000000000000000000000000000000000001
/// block_hash: 0x0000000000000000000000000000000000000000000000000000000000000002
/// commitment (poseidon_hash): 0x05d44a3decb2b2e0cc71071f7b802f45dd792d064f0fc7316c46514f70f9891a
#[test]
fn test_verify_katana_report_data_case_2() {
    let report_data = u512 {
        limb0: 0x452f807b1f0771cce0b2b2ec3d4ad405,
        limb1: 0x1a89f9704f51466c31c70f4f062d79dd,
        limb2: 0,
        limb3: 0,
    };

    let state_root: felt252 = 0x0000000000000000000000000000000000000000000000000000000000000001;
    let block_hash: felt252 = 0x0000000000000000000000000000000000000000000000000000000000000002;

    let result = verify_katana_report_data(report_data, state_root, block_hash);
    assert(result, 'Verification should pass');
}

/// Test case 3: Realistic block data
/// state_root: 0x04b1a39276c1df7ca78febcb6850f3649e826a3f6618e6ab30b48dcc948de1ad
/// block_hash: 0x06c5e8a47fb34d21c08e4eb6a91fa7bce3f2d5a490c8b7e1d26f43098a5bc7e2
/// commitment (poseidon_hash): 0x060b6465a73cb1456f7fadb742744d61321a68a24f6f1a36803fdf4e922719a3
#[test]
fn test_verify_katana_report_data_case_3() {
    let report_data = u512 {
        limb0: 0x614d7442b7ad7f6f45b13ca765640b06,
        limb1: 0xa31927924edf3f80361a6f4fa2681a32,
        limb2: 0,
        limb3: 0,
    };

    let state_root: felt252 = 0x04b1a39276c1df7ca78febcb6850f3649e826a3f6618e6ab30b48dcc948de1ad;
    let block_hash: felt252 = 0x06c5e8a47fb34d21c08e4eb6a91fa7bce3f2d5a490c8b7e1d26f43098a5bc7e2;

    let result = verify_katana_report_data(report_data, state_root, block_hash);
    assert(result, 'Verification should pass');
}

/// Test case 4: Commitment mismatch (should panic)
/// Uses wrong state_root for the report_data
#[test]
#[should_panic(expected: 'Commitment mismatch')]
fn test_verify_katana_report_data_mismatch() {
    // report_data was computed with state_root=0x1, block_hash=0x2
    let report_data = u512 {
        limb0: 0x452f807b1f0771cce0b2b2ec3d4ad405,
        limb1: 0x1a89f9704f51466c31c70f4f062d79dd,
        limb2: 0,
        limb3: 0,
    };

    // But we pass different state_root (0x3 instead of 0x1)
    let state_root: felt252 = 0x3;
    let block_hash: felt252 = 0x2;

    // This should panic with 'Commitment mismatch'
    verify_katana_report_data(report_data, state_root, block_hash);
}

/// Test that limb2 must be zero
#[test]
#[should_panic(expected: 'Report data limb2 must be 0')]
fn test_verify_katana_report_data_limb2_nonzero() {
    let report_data = u512 { limb0: 0, limb1: 0, limb2: 1, limb3: 0, };

    let state_root: felt252 = 0x123;
    let block_hash: felt252 = 0x456;

    verify_katana_report_data(report_data, state_root, block_hash);
}

/// Test that limb3 must be zero
#[test]
#[should_panic(expected: 'Report data limb3 must be 0')]
fn test_verify_katana_report_data_limb3_nonzero() {
    let report_data = u512 { limb0: 0, limb1: 0, limb2: 0, limb3: 1, };

    let state_root: felt252 = 0x123;
    let block_hash: felt252 = 0x456;

    verify_katana_report_data(report_data, state_root, block_hash);
}
