[workspace]
members = ["amd_tee_registry", "katana_tee", "scripts"]

[[tool.snforge.fork]]
name = "SEPOLIA_LATEST"
url = "$SEPOLIA_RPC_URL"
block_id.tag = "latest"

[[tool.snforge.fork]]
name = "MAINNET"
url = "$MAINNET_RPC_URL"
block_id.tag = "latest"

[lib]
sierra = true
casm = true
