use amd_tee_registry::journal_decode::decode_verifier_journal;

// Import generated fixtures (generated by: katana-tee generate-cairo-fixtures)
mod test_journal_decode_fixtures;
use test_journal_decode_fixtures::{
    get_block_0_expected, get_block_0_inputs, get_block_1_expected, get_block_1_inputs,
    get_block_2_expected, get_block_2_inputs,
};

/// Helper to compare VerifierJournal structs field by field for better error messages
fn assert_journal_eq(
    actual: amd_tee_registry::tee_types::VerifierJournal,
    expected: amd_tee_registry::tee_types::VerifierJournal,
) {
    assert(actual.result == expected.result, 'result mismatch');
    assert(actual.timestamp == expected.timestamp, 'timestamp mismatch');
    assert(actual.processor_model == expected.processor_model, 'processor_model mismatch');
    assert(
        actual.trusted_certs_prefix_len == expected.trusted_certs_prefix_len,
        'trusted_prefix mismatch',
    );

    // Compare raw_report array element by element
    assert(actual.raw_report.len() == expected.raw_report.len(), 'raw_report len mismatch');
    let mut i: u32 = 0;
    while i < actual.raw_report.len() {
        assert(*actual.raw_report.at(i) == *expected.raw_report.at(i), 'raw_report elem mismatch');
        i += 1;
    }

    // Compare certs array element by element
    assert(actual.certs.len() == expected.certs.len(), 'certs len mismatch');
    let mut j: u32 = 0;
    while j < actual.certs.len() {
        assert(*actual.certs.at(j) == *expected.certs.at(j), 'certs elem mismatch');
        j += 1;
    }

    // Compare cert_serials array element by element
    assert(actual.cert_serials.len() == expected.cert_serials.len(), 'serials len mismatch');
    let mut k: u32 = 0;
    while k < actual.cert_serials.len() {
        assert(*actual.cert_serials.at(k) == *expected.cert_serials.at(k), 'serials elem mismatch');
        k += 1;
    };
}

#[test]
fn test_decode_block_0() {
    let inputs = get_block_0_inputs();
    let expected = get_block_0_expected();
    let result = decode_verifier_journal(inputs.span());
    assert_journal_eq(result, expected);
}

#[test]
fn test_decode_block_1() {
    let inputs = get_block_1_inputs();
    let expected = get_block_1_expected();
    let result = decode_verifier_journal(inputs.span());
    assert_journal_eq(result, expected);
}

#[test]
fn test_decode_block_2() {
    let inputs = get_block_2_inputs();
    let expected = get_block_2_expected();
    let result = decode_verifier_journal(inputs.span());
    assert_journal_eq(result, expected);
}
