#!/bin/bash
# ==============================================================================
# REPRODUCE-RELEASE.SH - Reproduce a published release from source
# ==============================================================================
#
# One-command independent reproduction of a katana-tee-vm release:
#
#   git fetch --tags && git checkout <tag>
#   ./reproduce-release.sh <tag>
#
# The script:
#   1. Downloads the release's build-info.txt (the published provenance).
#   2. Downloads the exact katana binary the release embedded, verified
#      against the recorded KATANA_BINARY_SHA256.
#   3. Rebuilds OVMF + kernel + initrd from source with SOURCE_DATE_EPOCH
#      set to the recorded value (OVMF derives its own epoch from the pinned
#      OVMF commit — see scripts/build-ovmf.sh).
#   4. Compares every rebuilt artifact against the published SHA-256s and
#      re-derives the launch measurement, via verify-build.sh.
#
# Exit code 0 means: the artifacts you built from source are byte-identical
# to the published release, and they hash to the published launch
# measurement. You have independently reproduced the release.
#
# Expectations:
#   - Run on an Ubuntu host matching the release builder (ubuntu-latest at
#     build time). The initrd build downloads pinned Ubuntu .debs via apt,
#     and EDK2 output depends on the toolchain (gcc/nasm/iasl) — a different
#     OS image can yield a different (but still internally consistent)
#     OVMF.fd.
#   - The OVMF build takes ~10 minutes; the full run ~15.
#   - Docker is needed (static cryptsetup build), plus cargo with the
#     x86_64-unknown-linux-musl target (snp-derivekey).
#
# Usage:
#   ./reproduce-release.sh TAG [--workdir DIR]
#
# Environment:
#   KATANA_TEE_VM_REPO   Release source repo (default: dojoengine/katana)
#   KATANA_REPO          Katana binary repo  (default: dojoengine/katana)
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VM_REPO="${KATANA_TEE_VM_REPO:-dojoengine/katana}"
KATANA_REPO="${KATANA_REPO:-dojoengine/katana}"
TAG=""
WORKDIR=""

usage() {
    echo "Usage: $0 TAG [--workdir DIR]"
    echo ""
    echo "Reproduce release TAG (e.g. tee-vm-v0.1.0+katana-v1.8.0-rc.5) from source and"
    echo "compare against the published artifacts. Run from a clean checkout"
    echo "of the release tag."
    exit 1
}

die() {
    echo "ERROR: $*" >&2
    exit 1
}

log() {
    echo ""
    echo "==> $*"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --workdir)
            WORKDIR="${2:?--workdir requires a value}"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        -*)
            die "Unknown option: $1"
            ;;
        *)
            [[ -z "$TAG" ]] || usage
            TAG="$1"
            shift
            ;;
    esac
done
[[ -n "$TAG" ]] || usage

# ------------------------------------------------------------------------------
# Preflight
# ------------------------------------------------------------------------------
MISSING=()
for tool in git curl tar sha256sum cargo docker apt-get dpkg-deb nasm iasl cpio zstd; do
    command -v "$tool" >/dev/null 2>&1 || MISSING+=("$tool")
done
if [[ ${#MISSING[@]} -gt 0 ]]; then
    die "missing required tools: ${MISSING[*]} (this script expects an Ubuntu host with the build toolchain installed — see docs/release-pipeline.md)"
fi

# The build must run against exactly the tagged tree, or the rebuilt initrd
# (whose contents include the init script generated by build-initrd.sh)
# will not match the published bytes.
TAG_SHA="$(git -C "$SCRIPT_DIR" rev-parse -q --verify "refs/tags/${TAG}^{commit}" || true)"
[[ -n "$TAG_SHA" ]] || die "tag '$TAG' not found locally — run: git fetch --tags"
HEAD_SHA="$(git -C "$SCRIPT_DIR" rev-parse HEAD)"
[[ "$HEAD_SHA" == "$TAG_SHA" ]] || die "HEAD ($HEAD_SHA) is not the release tag — run: git checkout $TAG"
git -C "$SCRIPT_DIR" diff-index --quiet HEAD -- || die "working tree has uncommitted changes — reproduce from a clean checkout"

if [[ -z "$WORKDIR" ]]; then
    WORKDIR="$(mktemp -d /tmp/katana-tee-vm-reproduce.XXXXXX)"
fi
mkdir -p "$WORKDIR"
OUTPUT_DIR="$WORKDIR/output"

echo "=========================================="
echo "Reproducing release: $TAG"
echo "=========================================="
echo "  Source repo:   $VM_REPO"
echo "  Katana repo:   $KATANA_REPO"
echo "  Checkout:      $HEAD_SHA"
echo "  Work dir:      $WORKDIR"

# ------------------------------------------------------------------------------
# 1. Published provenance
# ------------------------------------------------------------------------------
log "Downloading published build-info"
BUILD_INFO="$WORKDIR/published-build-info.txt"
# The tag/asset name carries a '+' (SemVer build metadata); percent-encode it
# so curl sends a literal '+' in the URL path rather than a space.
TAG_URL="${TAG//+/%2B}"
curl -fsSL -o "$BUILD_INFO" \
    "https://github.com/${VM_REPO}/releases/download/${TAG_URL}/build-info-${TAG_URL}.txt" \
    || die "could not download build-info for release $TAG from $VM_REPO"

info_get() {
    awk -F= -v k="$1" '$1 == k { sub(/^[^=]*=/, ""); print; exit }' "$BUILD_INFO"
}

RECORDED_EPOCH="$(info_get SOURCE_DATE_EPOCH)"
RECORDED_KATANA_SHA="$(info_get KATANA_BINARY_SHA256)"
[[ -n "$RECORDED_EPOCH" ]] || die "published build-info has no SOURCE_DATE_EPOCH"
[[ -n "$RECORDED_KATANA_SHA" ]] || die "published build-info has no KATANA_BINARY_SHA256"
echo "  SOURCE_DATE_EPOCH:    $RECORDED_EPOCH"
echo "  KATANA_BINARY_SHA256: $RECORDED_KATANA_SHA"

# ------------------------------------------------------------------------------
# 2. The exact katana binary the release embedded
# ------------------------------------------------------------------------------
# The embedded katana version is attached to the VM tag as the SemVer build
# metadata suffix "+katana-<ver>" (and recorded as KATANA_VERSION in
# build-info); take it from the tag.
KATANA_VER="${TAG##*+katana-}"
[[ "$KATANA_VER" != "$TAG" ]] || die "tag '$TAG' has no +katana-<ver> suffix — not a tee-vm-v* release tag"
RECORDED_KATANA_VER="$(info_get KATANA_VERSION)"
if [[ -n "$RECORDED_KATANA_VER" && "$RECORDED_KATANA_VER" != "$KATANA_VER" ]]; then
    die "katana version mismatch: tag says '$KATANA_VER' but build-info records '$RECORDED_KATANA_VER'"
fi

log "Downloading katana $KATANA_VER (portable linux_amd64 build)"
KATANA_TARBALL="$WORKDIR/katana_${KATANA_VER}_linux_amd64.tar.gz"
curl -fsSL -o "$KATANA_TARBALL" \
    "https://github.com/${KATANA_REPO}/releases/download/${KATANA_VER}/katana_${KATANA_VER}_linux_amd64.tar.gz" \
    || die "could not download katana $KATANA_VER from $KATANA_REPO"

mkdir -p "$WORKDIR/katana-bin"
tar -xzf "$KATANA_TARBALL" -C "$WORKDIR/katana-bin"
KATANA_BIN="$(find "$WORKDIR/katana-bin" -type f -name katana -perm -u+x | head -n1)"
[[ -n "$KATANA_BIN" ]] || die "katana binary not found in downloaded tarball"

ACTUAL_KATANA_SHA="$(sha256sum "$KATANA_BIN" | awk '{print $1}')"
if [[ "$ACTUAL_KATANA_SHA" != "$RECORDED_KATANA_SHA" ]]; then
    die "katana binary sha256 mismatch:
  downloaded: $ACTUAL_KATANA_SHA
  recorded:   $RECORDED_KATANA_SHA
The katana release asset has changed since this release was built — the
initrd cannot be reproduced from it."
fi
echo "  katana binary verified: $ACTUAL_KATANA_SHA"

# ------------------------------------------------------------------------------
# 2b. The exact sidecar binaries the release embedded (if any)
# ------------------------------------------------------------------------------
# Releases from tee-vm-v0.2.0 bundle paymaster-service + vrf-server into the
# initrd and record their input sha256s in build-info. Earlier releases have
# no sidecar keys and reproduce without them.
RECORDED_PAYMASTER_SHA="$(info_get PAYMASTER_BINARY_SHA256)"
RECORDED_VRF_SHA="$(info_get VRF_BINARY_SHA256)"
SIDECAR_FLAGS=()
if [[ -n "$RECORDED_PAYMASTER_SHA" && -n "$RECORDED_VRF_SHA" ]]; then
    for sidecar in paymaster-service vrf-server; do
        log "Downloading $sidecar $KATANA_VER (linux_amd64 build)"
        curl -fsSL -o "$WORKDIR/${sidecar}.tar.gz" \
            "https://github.com/${KATANA_REPO}/releases/download/${KATANA_VER}/${sidecar}_${KATANA_VER}_linux_amd64.tar.gz" \
            || die "could not download $sidecar $KATANA_VER from $KATANA_REPO"
        mkdir -p "$WORKDIR/${sidecar}-bin"
        tar -xzf "$WORKDIR/${sidecar}.tar.gz" -C "$WORKDIR/${sidecar}-bin"
    done
    PAYMASTER_BIN="$(find "$WORKDIR/paymaster-service-bin" -type f -name paymaster-service | head -n1)"
    VRF_BIN="$(find "$WORKDIR/vrf-server-bin" -type f -name vrf-server | head -n1)"
    [[ -n "$PAYMASTER_BIN" ]] || die "paymaster-service binary not found in downloaded tarball"
    [[ -n "$VRF_BIN" ]] || die "vrf-server binary not found in downloaded tarball"
    ACTUAL_PAYMASTER_SHA="$(sha256sum "$PAYMASTER_BIN" | awk '{print $1}')"
    [[ "$ACTUAL_PAYMASTER_SHA" == "$RECORDED_PAYMASTER_SHA" ]] || die "paymaster-service sha256 mismatch:
  downloaded: $ACTUAL_PAYMASTER_SHA
  recorded:   $RECORDED_PAYMASTER_SHA
The release asset has changed since this release was built — the initrd
cannot be reproduced from it."
    ACTUAL_VRF_SHA="$(sha256sum "$VRF_BIN" | awk '{print $1}')"
    [[ "$ACTUAL_VRF_SHA" == "$RECORDED_VRF_SHA" ]] || die "vrf-server sha256 mismatch:
  downloaded: $ACTUAL_VRF_SHA
  recorded:   $RECORDED_VRF_SHA
The release asset has changed since this release was built — the initrd
cannot be reproduced from it."
    chmod +x "$PAYMASTER_BIN" "$VRF_BIN"
    SIDECAR_FLAGS=(--paymaster-bin "$PAYMASTER_BIN" --vrf-bin "$VRF_BIN")
    echo "  sidecar binaries verified: $ACTUAL_PAYMASTER_SHA / $ACTUAL_VRF_SHA"
elif [[ -n "$RECORDED_PAYMASTER_SHA" || -n "$RECORDED_VRF_SHA" ]]; then
    die "published build-info records only one sidecar sha256 — corrupt provenance"
else
    echo "  build-info records no sidecar sha256s — pre-sidecar release, building without them"
fi

# ------------------------------------------------------------------------------
# 3. Rebuild everything from source
# ------------------------------------------------------------------------------
log "Building OVMF + kernel + initrd (SOURCE_DATE_EPOCH=$RECORDED_EPOCH; expect ~15 minutes)"
export SOURCE_DATE_EPOCH="$RECORDED_EPOCH"
"$SCRIPT_DIR/build.sh" --katana "$KATANA_BIN" ${SIDECAR_FLAGS[@]+"${SIDECAR_FLAGS[@]}"} --install "$OUTPUT_DIR"

# ------------------------------------------------------------------------------
# 4. Compare against the published release
# ------------------------------------------------------------------------------
# verify-build.sh checks the artifacts in a directory against the
# build-info.txt next to them. Swap in the PUBLISHED build-info so the
# comparison is built-from-source vs published-provenance (including the
# recorded launch measurement), not built vs itself.
log "Comparing rebuilt artifacts against published provenance"
cp "$BUILD_INFO" "$OUTPUT_DIR/build-info.txt"

# verify-build.sh needs snp-digest to re-derive the measurement.
if ! command -v snp-digest >/dev/null 2>&1 \
   && [[ -z "$(find "$SCRIPT_DIR/snp-tools/target" -type f -name snp-digest -perm -u+x 2>/dev/null | head -n1)" ]]; then
    log "Building snp-digest"
    (cd "$SCRIPT_DIR/snp-tools" && cargo build --release --locked)
fi

if "$SCRIPT_DIR/verify-build.sh" "$OUTPUT_DIR"; then
    echo ""
    echo "=========================================="
    echo "REPRODUCED: artifacts built from source match release $TAG"
    echo "=========================================="
    exit 0
else
    echo ""
    echo "=========================================="
    echo "REPRODUCTION FAILED for $TAG — see mismatches above."
    echo "Most common cause: a different OS toolchain than the release"
    echo "builder (EDK2/OVMF output depends on gcc/nasm/iasl versions)."
    echo "Artifacts kept in: $OUTPUT_DIR"
    echo "=========================================="
    exit 1
fi
