name: build and push workflow base image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest-4-cores

    outputs:
      tag_name: ${{ steps.release_info.outputs.tag_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker image tag
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c 1-7)
          echo "DOCKER_TAG=$SHORT_SHA" >> $GITHUB_ENV

      - name: Set outputs
        id: release_info
        run: |
          echo "tag_name=${{ env.DOCKER_TAG }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: ghcr.io/${{ github.repository }}-runner:latest,ghcr.io/${{ github.repository }}-runner:${{ env.DOCKER_TAG }}
          build-args: |
            RUST_VERSION=1.83.0
            BUILD_TYPE=${{ github.event_name }}
            DOJO_VERSION=1.2.2
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}-runner:latest
