name: ci

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.83.0

jobs:
  fmt:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dojoengine/dojo-dev:v1.2.2
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: scripts/rust_fmt.sh --check

  build:
    runs-on: ubuntu-latest
    needs: fmt
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo build -r --bin katana
          mkdir -p bins
          cp ./target/release/katana bins
      - uses: actions/upload-artifact@v4
        with:
          name: katana-bin
          path: bins

  # This job is used to ensure the built katana image doesn't depend on any
  # libraries that don't exist in the base docker image we use for distribution
  ensure-docker:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: katana-bin
      - run: |
          chmod +x ./katana
          ./katana &
          KATANA_PID=$!
          sleep 2
          if ! kill -0 $KATANA_PID; then
          echo "Katana exited with an error"
          exit 1
          fi
          kill $KATANA_PID

  test-cairo-native:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dojoengine/dojo-dev:v1.2.2
    env:
      MLIR_SYS_190_PREFIX: /usr/lib/llvm-19/
      LLVM_SYS_191_PREFIX: /usr/lib/llvm-19/
      TABLEGEN_190_PREFIX: /usr/lib/llvm-19/
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Add LLVM deb repository
        uses: myci-actions/add-deb-repo@11
        with:
          repo-name: llvm-repo
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
          repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main
      - run: sudo apt-get update && sudo apt-get upgrade -y
      - name: Install Cairo native dependencies
        run: |
          make native-deps
      - uses: actions/download-artifact@v4
        with:
          name: katana-bin
          path: /tmp/bins
      - run: |
          export PATH=/tmp/bins:$PATH
          chmod +x /tmp/bins/katana
          tar -xzf tests/fixtures/katana_db.tar.gz -C /tmp/
          cargo llvm-cov nextest --no-report --all-features --workspace
          cargo llvm-cov report --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info

  snos-integration-test:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dojoengine/dojo-dev:v1.2.2
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo run -p snos-integration-test
