name: Dev Image Test

on:
  pull_request:
    paths:
      - ".github/Dockerfile"

env:
  RUST_VERSION: 1.86.0
  CLIPPY_VERSION: nightly-2025-02-20

jobs:
  build-dev-image:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    strategy:
      matrix:
        platform: [linux/amd64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1

      - name: Test Docker build for ${{ matrix.platform }}
        uses: useblacksmith/build-push-action@v2
        with:
          push: false
          file: .github/Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: |
            RUST_VERSION=${{ env.RUST_VERSION }}
            CLIPPY_VERSION=${{ env.CLIPPY_VERSION }}
