name: generate-test-databases

on:
  workflow_dispatch:
    inputs:
      dojo_tag:
        description: 'Dojo repository tag to use (e.g., v1.6.0). Leave empty for main branch.'
        required: false
        default: ''
        type: string
  schedule:
    # Run weekly on Sundays at 00:00 UTC
    - cron: '0 0 * * 0'

jobs:
  generate-databases:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/dojoengine/katana-dev:latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
      
      # Workaround for https://github.com/actions/runner-images/issues/6775
      - run: git config --global --add safe.directory "*"
      
      - uses: Swatinem/rust-cache@v2
        with:
          key: generate-db-${{ github.job }}
      
      - name: Setup Dojo
        uses: dojoengine/setup-dojo@v0.1.0
        with:
          version: latest
      
      - name: Generate simple test database
        run: |
          if [ -n "${{ github.event.inputs.dojo_tag }}" ]; then
            echo "Generating simple test database from Dojo tag: ${{ github.event.inputs.dojo_tag }}"
            ./scripts/generate-simple-db.sh "${{ github.event.inputs.dojo_tag }}"
          else
            echo "Generating simple test database from Dojo main branch"
            ./scripts/generate-simple-db.sh
          fi
      
      - name: Check for changes
        id: check_changes
        run: |
          # Determine which file to check based on whether a tag was provided
          if [ -n "${{ github.event.inputs.dojo_tag }}" ]; then
            DB_FILE="tests/fixtures/db/simple-${{ github.event.inputs.dojo_tag }}.tar.gz"
          else
            DB_FILE="tests/fixtures/db/simple.tar.gz"
          fi
          
          if git diff --quiet "$DB_FILE" 2>/dev/null; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in test database"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Test database has changed or is new"
          fi
          echo "db_file=$DB_FILE" >> $GITHUB_OUTPUT
      
      - name: Get version info
        if: steps.check_changes.outputs.changes == 'true'
        id: version_info
        run: |
          DATE=$(date +%Y%m%d%H%M%S)
          SHORT_SHA=$(cd /tmp/dojo 2>/dev/null && git rev-parse --short HEAD || echo "unknown")
          echo "version=db-update-${DATE}" >> $GITHUB_OUTPUT
          echo "dojo_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          delete-branch: true
          token: ${{ secrets.CREATE_PR_TOKEN || secrets.GITHUB_TOKEN }}
          add-paths: ${{ steps.check_changes.outputs.db_file }}
          branch: ${{ steps.version_info.outputs.version }}
          title: "chore(test): update simple test database${{ github.event.inputs.dojo_tag && format(' ({0})', github.event.inputs.dojo_tag) || '' }}"
          commit-message: |
            chore(test): update simple test database${{ github.event.inputs.dojo_tag && format(' ({0})', github.event.inputs.dojo_tag) || '' }}
            
            Generated from Dojo repository (commit: ${{ steps.version_info.outputs.dojo_sha }})
            ${{ github.event.inputs.dojo_tag && format('Tag: {0}', github.event.inputs.dojo_tag) || 'Branch: main' }}
          body: |
            ## Automated Test Database Update
            
            This PR updates the simple test database used for integration tests.
            
            ### Details
            - **Dojo Version**: `${{ github.event.inputs.dojo_tag || 'main (latest)' }}`
            - **Dojo Commit**: `${{ steps.version_info.outputs.dojo_sha }}`
            - **Generated at**: `${{ steps.version_info.outputs.version }}`
            
            ### Changes
            - Updated `${{ steps.check_changes.outputs.db_file }}` with Dojo simple example data
            
            ---
            *This PR was automatically generated by the test database update workflow.*